# Application custom properties
app:
  client:
    allowedOrigin: http://localhost:4200
  # Security configuration
  jwt:
    secret: asd3icvzASC99adml_e7Iiod0sdfa-dfa9865vB18cy65kjJ
  security:
    permitall: false
    maximumLoginAttempts: 3
    loginAttemptsExpiration: 5

# Path to the error controller may be customized here
server:
  error:
    path: /error

# Logging properties
logging:
  level:
    io.dpopkov.knowthenix.DataInitialization: DEBUG
    io.dpopkov.knowthenix.rest.controllers: TRACE
    io.dpopkov.knowthenix.services: TRACE
    io.dpopkov.knowthenix.security: TRACE
#    io.dpopkov.knowthenix.config.JwtAuthorizationFilter: TRACE
