spring:
  datasource:
    url: jdbc:mysql://localhost:3306/knowthenix-prod?userUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${KNOWTHENIX_ADMIN}
    password: ${KNOWTHENIX_ADMIN_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
    # After Hibernate schema creation is performed then additionally data.sql is executed to populate the db
    defer-datasource-initialization: true
  h2:
    console:
      enabled: false
  # Set init platform H2 for using data-h2.sql script
  sql:
    init:
      mode: always

# Application custom properties
app:
  data:
    init: true
