# Application custom properties
app:
  client:
    allowedOrigin: http://localhost:4200

# Logging properties
logging:
  level:
    io.dpopkov.knowthenix.DataInitialization: DEBUG
    io.dpopkov.knowthenix.rest.controllers: DEBUG
